name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Build the project
      run: |
        cd src
        make

    - name: Run the program
      run: |
        cd src
        ./main

    - name: Run make check
      run: |
        cd src
        make check

    - name: Run make distcheck
      run: |
        cd src
        make distcheck
